# Generated by Django 2.2.1 on 2019-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
