# Generated by Django 2.2.1 on 2019-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190611_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
