# Generated by Django 2.2.1 on 2019-06-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190611_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
