# Generated by Django 2.2.1 on 2019-06-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20190611_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mname',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
