# Generated by Django 2.2.1 on 2019-06-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190611_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
