# Generated by Django 2.2.1 on 2019-06-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_user_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
