# Generated by Django 2.2.1 on 2019-06-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=5),
        ),
    ]
