# Generated by Django 2.2.1 on 2019-06-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
