# Generated by Django 2.2.1 on 2019-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
