# Generated by Django 2.2.1 on 2019-06-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_user_queasked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='queasked',
        ),
    ]
