# Generated by Django 2.2.1 on 2019-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_remove_user_queasked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queasked',
            field=models.IntegerField(default=0),
        ),
    ]
