# Generated by Django 2.2.1 on 2019-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_user_queasked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('funame', models.CharField(max_length=30)),
                ('describ', models.CharField(max_length=100)),
            ],
        ),
    ]
