# Generated by Django 2.2.1 on 2019-06-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_answer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='idanswer',
            field=models.IntegerField(default=0),
        ),
    ]
