# Generated by Django 2.2.1 on 2019-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_answer_idanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
