# Generated by Django 2.2.1 on 2019-06-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_answer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.CharField(default='', max_length=250),
        ),
    ]
