# Generated by Django 2.2.1 on 2019-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='asked',
            field=models.CharField(default='', max_length=50),
        ),
    ]
