# Generated by Django 2.2.1 on 2019-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_answer_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='totalans',
            field=models.IntegerField(default=0),
        ),
    ]
