# Generated by Django 2.2.1 on 2019-06-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_question_totalans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ansgive',
            field=models.IntegerField(default=0),
        ),
    ]
