# Generated by Django 2.2.1 on 2019-06-22 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_answer_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
