# Generated by Django 2.2.1 on 2019-06-22 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_auto_20190622_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
