# Generated by Django 2.2.1 on 2019-06-22 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_auto_20190622_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
