# Generated by Django 2.2.1 on 2019-06-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
