# Generated by Django 2.2.1 on 2019-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_answer_ansupvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ansupvoted',
        ),
        migrations.AddField(
            model_name='user',
            name='ansupvoted',
            field=models.IntegerField(default=0),
        ),
    ]
