# Generated by Django 2.2.1 on 2019-06-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_user_ansdownvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ansdownvoted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ansupvoted',
        ),
    ]
