# Generated by Django 2.2.1 on 2019-06-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0042_auto_20190623_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='personid',
        ),
    ]
