# Generated by Django 2.2.1 on 2019-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0044_auto_20190623_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rid',
            field=models.IntegerField(default=0),
        ),
    ]
