# Generated by Django 2.2.1 on 2019-06-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0045_review_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imgpicture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
