# Generated by Django 2.2.1 on 2019-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0046_user_imgpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=300, null=True)),
                ('email', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
